name: 'PR: Validate, Test and Danger'

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate:
    name: ✅ Validate project
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout project
        uses: actions/checkout@v2

      - name: 🟢 Setup NodeJS
        uses: actions/setup-node@v2

      - name: 📥 Install dependencies
        run: yarn

      - name: 🖍️ Check types
        run: yarn check:types

      - name: 💅 Check format
        run: yarn check:format

      - name: 📑 Check lint
        run: yarn check:lint

      - name: 🔤 Check spelling
        run: yarn check:spelling

  test:
    name: 🧑‍🔬 Test project
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: ⬇️ Checkout project
        uses: actions/checkout@v2

      - name: 🟢 Setup NodeJS
        uses: actions/setup-node@v2

      - name: 📥 Install dependencies
        run: yarn

      - name: 🧪 Run the tests
        run: yarn test:coverage

      - name: 📊 Generate coverage report
        uses: hrgui/lcov-reporter-action@v0.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  danger:
    name: 👩🏻‍💻 Danger
    runs-on: ubuntu-latest
    needs: test
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: ⬇️ Checkout project
        uses: actions/checkout@v2

      - name: 🟢 Setup NodeJS
        uses: actions/setup-node@v2

      - name: 📥 Install dependencies
        run: yarn

      - name: 👩🏻‍💻 Run the danger
      - run: yarn danger ci
